### PR TITLE
Darwinia nft claims in pordria

### PR DESCRIPTION
**Pull request by hujw77**
- Darwinia claims
- August 2022 NFT reward, tx hash: 0x938afb1ed43d3be21e546e062d8fcd02c4df9896b69b0aed4794bff665387778

### CODE REVIEW

**Comment by JayJay1024** [comment]
Should we add a `data/darwinia` ?

image

**Comment by hujw77** [comment]
> Should we add a `data/darwinia` ?
> 
> image

The directory name means which network to claim the rewards.

**Comment by JayJay1024** [comment]
> The directory name means which network to claim the rewards.
Both Darwinia and Crab need to claim the reward

**Comment by hujw77** [comment]
> > The directory name means which network to claim the rewards.
> 
> Both Darwinia and Crab need to claim the reward

And all the reward claimed on Crab @1022ranji

**Comment by JayJay1024** [comment]
Are we adding to this repo and not the https://github.com/evolutionlandorg/claims because this is darwinia and not evo?

**Comment by hujw77** [comment]
> Are we adding to this repo and not the https://github.com/evolutionlandorg/claims because this is darwinia and not evo?

Yes, any project could fork a claims repo, and make a pr to pordria to support their project.

**Review by JayJay1024 — APPROVED** [review]

**Pull request merged**
